### ISSUE TITLE
calling only --with-xcover still breaks at can't use both flags

### ISSUE THREAD

**Issue by p00j4** [cmheisel/nose-xcover#28]
**Actual:**
Tried using only "--with-xcover" or "--with-xcoverage" but it keeps stopping at error
<img width="916" alt="screen shot 2016-09-06 at 6 01 26 pm" src="https://cloud.githubusercontent.com/assets/12966925/18273739/7b32da64-745c-11e6-9cd4-99ef3acd5c28.png">

its weird, because as per lines [44-46](https://github.com/cmheisel/nose-xcover/blob/master/nosexcover/nosexcover.py) this shouldn't have been a problem. 
Is there any possibility of "options.enable_plugin_coverage" returning `true` by default?
![image](https://cloud.githubusercontent.com/assets/12966925/18273847/14b1ff1c-745d-11e6-9cb5-573ce4009233.png)

**Comment by p00j4** [comment]
Noticed a pattern
it happens when I try to run nosetets on complete directory like
`nosetests ./tests/ --withxcover`

but when I run on particular file `nosetests ./tests/common/apis/test_homepage.py --withxcover` 
it works without complain 
But I need to run on the whole directory instead of single file, any suggestions?

**Comment by p00j4** [comment]
it not an issue so closing https://github.com/cmheisel/nose-xcover/issues/11#issuecomment-244949227
@cmheisel : i'm thinking to raise PR with change of error message & log little more convenient & self understood, should I go ahead?

**Comment by cmheisel** [comment]
@p00j4 -- Sure thing, I'd gladly welcome a PR like that!

**Comment by p00j4** [comment]
@cmheisel : could you please review & take in: https://github.com/cmheisel/nose-xcover/pull/29
